---

- name: Apply Base Configs
  hosts: switches
  gather_facts: no
  become: yes
  become_method: enable

  tasks:

    - name: Apply Base Configs
      eos_config:
        src: "backup_configs/{{ inventory_hostname }}-isis.cfg"
        replace: config
        save_when: always

